Draft: Adding cancellation tokens where needed
DomainBlocks/domain-blocks pull request #69
Opened 2022-10-05 09:57 UTC by carlosrfernandez

Aims to fix #66

2022-10-09 17:20 UTC, daniel-smith commented on src/DomainBlocks.Persistence.EventStore/EventStoreSnapshotRepository.cs
> +    public async Task SaveSnapshotAsync<TState>(
We need to sort out common formatting rules in this project as well :)

2022-10-09 17:41 UTC, daniel-smith requested changes
Nice one, definitely good to sort this out. I've just added a few comments to look through.

2022-10-09 17:41 UTC, daniel-smith commented on src/DomainBlocks.Persistence.EventStore/EventStoreSnapshotRepository.cs
> +            _serializer.ToEventData(
Is this new call to `ToEventData` needed?

2022-10-09 17:41 UTC, daniel-smith commented on src/DomainBlocks.Persistence/IEventsRepository.cs
> +    Task<long> SaveEventsAsync(
Again, common code style would be good. It's a little hard to see what's actually changed amongst the formatting changes. Not for this PR, but let's prioritise this.

2022-10-09 17:41 UTC, daniel-smith commented on src/DomainBlocks.Projections.EventStore/EventStoreDroppedSubscriptionHandler.cs
> +                    "Exception occurred in subscriber. Stopping event publisher. Reason {Reason}",
Looks to be only formatting changes in this file, as far as I can see.

2022-10-09 17:41 UTC, daniel-smith commented on src/DomainBlocks.Projections.EventStore/EventStoreEventPublisher.cs
> +            () => ReSubscribeAfterDrop(CancellationToken.None));
Is passing in `CancellationToken.None` the right thing to do here?

2022-10-09 17:41 UTC, daniel-smith commented on src/DomainBlocks.Projections.EventStore/EventStoreEventPublisher.cs
> +                "changeit"),
I know this isn't related to this PR, but we should probably have these credentials configurable at some point!

2022-10-09 17:41 UTC, daniel-smith commented on src/DomainBlocks.Projections/EventDispatcher.cs
> +    public async Task StartAsync(CancellationToken cancellationToken)
Should we be consistent with having all our cancellation tokens as optional parameters - i.e. `= default`?

2022-10-09 17:41 UTC, daniel-smith commented on src/DomainBlocks.Projections.Tests/SqlCommandTests.cs
> +            await scenario.Dispatcher.StartAsync(default);
If the token was optional, we wouldn't have to pass `default` in these method calls.

2022-10-09 17:41 UTC, daniel-smith commented on src/DomainBlocks.Persistence.EventStore/EventStoreSnapshotRepository.cs
> +    public async Task SaveSnapshotAsync<TState>(
(not for this PR, btw)

2022-10-11 14:17 UTC, carlosrfernandez commented on src/DomainBlocks.Persistence.EventStore/EventStoreSnapshotRepository.cs
> +            _serializer.ToEventData(
This was a mistake from rebasing... mmmm

2022-10-11 14:18 UTC, carlosrfernandez commented on src/DomainBlocks.Projections.EventStore/EventStoreDroppedSubscriptionHandler.cs
> +                    "Exception occurred in subscriber. Stopping event publisher. Reason {Reason}",
I removed the string interpolation and sent it as a structured log. Maybe I shouldn't have included it as part of this PR.

2022-10-11 14:21 UTC, carlosrfernandez commented on src/DomainBlocks.Projections.EventStore/EventStoreEventPublisher.cs
> +            () => ReSubscribeAfterDrop(CancellationToken.None));
Yes fixed this

2022-10-11 14:25 UTC, carlosrfernandez commented on src/DomainBlocks.Projections/EventDispatcher.cs
> +    public async Task StartAsync(CancellationToken cancellationToken)
Done

2022-10-11 14:34 UTC, daniel-smith commented on src/DomainBlocks.Persistence/IAggregateRepository.cs
> +        AggregateLoadStrategy loadStrategy = AggregateLoadStrategy.PreferSnapshot,
Not for this PR, but we should consider moving `AggregateLoadStrategy` to the config side of things. I'm not sure how you want to load aggregates is going to change at load time. I'm also saying this because it's annoying that we now have to used a named arg for the cancellation token everywhere :)

2022-10-11 14:35 UTC, daniel-smith commented on src/DomainBlocks.Persistence/IAggregateRepository.cs
> +        Func<LoadedAggregate<TAggregateState>, bool> snapshotPredicate = null,
Same comment re `snapshotPredicate`. Not sure that will change at runtime. Let's consider moving this to config.

2022-10-11 14:35 UTC, daniel-smith approved these changes

2022-10-13 13:36 UTC, merged